### ISSUE TITLE
[FR] Enlarge space for CSL model from 24 to 40 characters in LTAPIBulkInfoTexts.

### ISSUE THREAD

**Issue by slgoldberg** [TwinFan/LTAPI#4]
LTAPI is currently truncating the returned CSL model (in `info.cslModel`) to 24 characters, where the last few characters form an ellipsis.

Unfortunately, this makes some CSL model path names ambiguous as a result.

In particular, the current BlueBell collection has a directory named `BB_Leipzig_Air_VA`, which alone is already 17/23 available characters. :-)

So for example, it's not possible today as a client of this API to disambiguate between:
```
BB_Leipzig_Air_VA E145
```
and
```
BB_Leipzig_Air_VA E170
```
... since they're both truncated to:
```
BB_Leipzig_Air_VA E1...
```

For most other models, there is enough disambiguation to fit in those _two_ available characters (!!), but it's a close call.

As a client of this API, I would much prefer not to make this change break other things -- so, I'd suggest two solutions that are "quick and dirty" if you are open to them, and a longer-term solution that would obviate this altogether:

## Option 1:
**Change bulk info texts to allocate 40 characters** for `cslName`, instead of 24, and change truncation logic accordingly.

Drawback: Obviously, this requires more versioning work, i.e. adding yet another version check based on the size of the struct, to handle compatibility.

However, aside from clients needing to update to the new version as well, it doesn't change any features that the client cares about -- it simply allows, as in my case, better disambiguation based on the CSL model path strings.

## Option 2:
**Don't add the ellipsis (`"..."`)** at the end!

In other words, truncate to 24 characters by setting only the 24th character to the null terminator (`'\0'`), instead of filling the last three characters with the ellipsis dots before the terminator.)

This way, the effective available space remaining for the example above actually _doubles_ (from 2 to 4 characters).

As a result, the Leipzig Air example above would now be different, i.e.:
```
BB_Leipzig_Air_VA E145
```
and
```
BB_Leipzig_Air_VA E170
```
... which fit exactly in the available 23 characters (excluding the null terminator) and fully disambiguates the two aircraft models.

Drawback: Of course, this method doesn't really solve anything, it mitigates the issue for similarly-named models. However, it is fragile in that any other long model directory names would cause this issue to possibly resurface. However, since this is already pretty fragile, that may be okay in this case until one of the other solutions is adopted (as a stop-gap).

## Option 3 (long term):
**Provide distilled model information instead** of (or in addition to) the CSL (and equivalent) model names.

Possibly in a future version, you could dispense with model names altogether and replace this part of the API with numeric values which are all my particular use-case needs.  I.e., instead of (or in addition to) the model name, what I really need is:
```cpp
 float size,         // max acf length in m (i.e., nose to tail)
 float height,       // max acf height in m (top to bottom of wheels)
 float wingspan,     // max acf width in m (wingtip to wingtip)
 float vert_offset,  // vertical offset in m from COG (higher/lower)
 float lat_offset    // lateral offset in m from COG (fwd/back)
```

With something equivalent to the above data, I would not need the `cslModel` string, nor in fact the weight-class (except perhaps as a nice-to-have to show users in an info screen).

This would be for _what you actually rendered_, not simply echoing data you're aggregating from any source channel.

## Conclusion / roll-out considerations:
Whichever solution you pick, the nice thing is that roll-out is pretty easy, since I believe (?) I'm the only client of this particular API feature today. (So, thank you for adding it for me!)

But moreover, since the fix would simply disambiguate two (if not more) models correctly, it would "just work" for me once it's fixed and I import the library.

I.e., I wouldn't need to change anything on my side, since the table that I've built internally for the data above is keyed off the disambiguated versions of those names.

So, once they're no longer ambiguous, they'll just work better.

Thanks.

**Comment by TwinFan** [comment]
Implemented both options 1 and 2 as per LiveTraffic v2.40:

- Extended `cslModel` to 40 chars as per LiveTraffic v2.40
- If feeding an older LTAPI plugin with the shorter 24 char `cslModel` field then don't add `...`

For option 3 I simply don't have the data.

**Comment by slgoldberg** [comment]
Thank you!  This is most excellent.  (Note: I have not had time yet to try it out, but it should be good. I'm so glad you thought ahead and came up with a way to version the API for things like this!)

Also, re: option 3:  I actually meant to withdraw that suggestion -- because I've convinced myself that model names (with optional paths to disambiguate duplicate names, as you do here) are much better and more applicable to other uses as well.  This is especially because I will always have to do some kind of name-based lookup for other cases (i.e. other plugins that don't have as good of an API).

So instead, I can (and do) simply have a curated database mapping each unique model name from various plugins into a set of all the values enumerated above for each plugin+model family. (Where "family" in this case only really applies to XPMP2-based CSL/X-CSL models.)

That method works great -- since today, ABC can customize the camera position for multiple models of the same logical aircraft, i.e. whether provided by Traffic Global, World Traffic, LiveTraffic (and xPilot and XPMP2 Remote Client), or a .acf file (as an AI aircraft in the native X-Plane AI system).

Thanks again!
